architecture: v0.1.5
callback_patience: 100
codes:
- ask_content
- ask_support
- how_are_you
- normal_response
- ping
- response_refusal
- who_are_you
dataset_name: clair
embedding_model: https://www.kaggle.com/models/google/universal-sentence-encoder/tensorFlow2/multilingual/2
epochs: 1000
l1_reg: 0.001
l2_reg: 0.001
learning_rate: 0.0001
min_words: 1
sent_dropout: 0.5
sent_hl_units: 64
stop_words_file: null
task: train
validation_split: 0.25
wandb_project: intent_classifier
